spring:
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성 SessionFactory가 시작될때 Drop, Create, alter 종료될때 Drop
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
#    open-in-view: false
jwt:
  key: localTestGood1234123412341234123412341234123412341234123412341234123412341234
  access-token-expiration-minutes: 420
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com
logging:
  file:
    name: sever.log
    path: /Users/user/Workspace/seb41_25
